App Submission: Obsidian
getumbrel/umbrel-apps pull request #1921
Opened 2024-12-11 15:50 UTC by al-lac

# App Submission

Obsidian

Fixes #1327

### 256x256 SVG icon
https://en.m.wikipedia.org/wiki/File:2023_Obsidian_logo.svg

### Gallery images
![CleanShot 2024-12-11 at 16 47 51](https://github.com/user-attachments/assets/84665bfe-1862-4b00-8f2d-ce86010eff1b)
![CleanShot 2024-12-11 at 16 48 42](https://github.com/user-attachments/assets/40bf702d-66de-46a9-aa76-16d477784922)
![CleanShot 2024-12-11 at 16 49 36](https://github.com/user-attachments/assets/79c7c913-dd7b-444c-85b8-fe3931a077da)

### I have tested my app on:
- [x] umbrelOS on a Raspberry Pi
- [ ] umbrelOS on an Umbrel Home
- [ ] umbrelOS on Linux VM

2024-12-17 18:25 UTC, sharknoon requested changes
Thank you @al-lac for another awesome submission 😀 I have left two minor suggestions below.

One note regarding some manifest keys being optional, while others arent. The reason is, that on some older umbrelOS versions ommiting for example the `path` key would lead to issues. That is why some keys can be omitted while others can't.

2024-12-17 18:25 UTC, sharknoon commented on obsidian/umbrel-app.yml
> +torOnly: false
`torOnly: false` cen be omitted, as it is already the default
```suggestion
```

2024-12-17 18:25 UTC, sharknoon commented on obsidian/umbrel-app.yml
> +deterministicPassword: false
This is already the default and can be omitted
```suggestion
```

2024-12-18 14:51 UTC, sharknoon approved these changes
Thank you @al-lac 
@nmfretz Looks good to me 👍

2025-01-13 01:50 UTC, nmfretz commented
Excellent, thanks for yet another app @al-lac! And thanks for the review @sharknoon.

I have reviewed and tested and it is working well. I made some very minor tweaks to tagline and app description. Going live!

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/9f5d7463-5baa-4e32-b9eb-edc839461252" />

2025-01-13 01:50 UTC, merged