App Submission: Mainsail
getumbrel/umbrel-apps pull request #1982
Opened 2024-12-23 21:31 UTC by Julienpeps

# App Submission

### Mainsail
A modern and responsive user interface for Klipper. Control and monitor your printer from everywhere, from any device.

This application will not work on its own, as it requires a Klipper server along with a Moonraker service running either on another device, or another container on umbrel.

It might be surprising to see that there is no persistent storage in the application's configuration, but that's normal. There is very little data to be stored on Mainsail's side, and the settings are actually stored in the client's browser.

### 256x256 SVG icon
The SVG from Mainsail's repo:
https://raw.githubusercontent.com/mainsail-crew/mainsail/refs/heads/develop/public/img/logo.svg

### Gallery images
I am currently unable to add any screenshots from the app myself, as I am still waiting on my printer, but there are some screenshots on the documentation's main page: https://docs.mainsail.xyz/

I will update if necessary.

### I have tested my app on:
- [x] umbrelOS on a Raspberry Pi
- [ ] umbrelOS on an Umbrel Home
- [ ] umbrelOS on Linux VM

2025-02-12 16:11 UTC, al-lac requested changes
Really great and clean submission @Julienpeps! 

I added some suggestions on what could be changed to get this ready.

@nmfretz looks pretty good to me, after some changes we could go ahead with it.

2025-02-12 16:11 UTC, al-lac commented on mainsail/docker-compose.yml
> +      - ${APP_DATA_DIR}/config.json:/usr/share/nginx/html/config.json:ro
Change to data directory after creating it.
```suggestion
      - ${APP_DATA_DIR}/data/config.json:/usr/share/nginx/html/config.json:ro
```

2025-02-12 16:11 UTC, al-lac commented on mainsail/umbrel-app.yml
> +  100% open source. Anyone can join, anyone can contribute.
Adapt the description a little bit to make it more readable.
```suggestion
tagline: Control and monitor your printer from everywhere, from any device.
description: >-
  🖨️ A modern and responsive user interface for Klipper. Control and monitor your printer from everywhere, from any device.


  **Easy to use.** The focus lies on both anticipating what users may need to do and ensuring that the user interface contains elements that are easily accessible, understandable, and user-friendly to make those actions easier.


  **Always one step ahead.** We work closely with developers of other projects so that functions can already be implemented early on.


  **100% open source.** Anyone can join, anyone can contribute.
```

2025-02-12 16:11 UTC, al-lac commented on mainsail/umbrel-app.yml
> +developer: Mainsail-Crew
```suggestion
developer: Mainsail Crew
```

2025-02-13 05:32 UTC, nmfretz reviewed
Thanks for another app submission @Julienpeps! And thanks a bunch for reviewing @al-lac 🤝.

We'll get gallery assets prepared in the meantime.

2025-02-13 05:32 UTC, nmfretz commented on mainsail/docker-compose.yml
> +    restart: on-failure
Can we try adding `user: "1000:1000"` here so that the container runs as non-root and see if everything still works?

It's not a deal-breaker or anything, it's just nice to run as non-root when not strictly required.

2025-02-13 05:32 UTC, nmfretz commented on mainsail/umbrel-app.yml
> +port: 8080
This port is already taken by the Lightning Node app. `8070` is free.

2025-02-13 07:09 UTC, al-lac commented on mainsail/docker-compose.yml
> +    restart: on-failure
Ah sorry forgot to post that. Already tried, does not work sadly. Fails to start with a lot of permission errors.

2025-02-14 02:35 UTC, nmfretz commented on mainsail/docker-compose.yml
> +    restart: on-failure
ah darn. Thanks for looking into that!

2025-02-17 00:13 UTC, nmfretz commented
@Julienpeps gallery assets are ready:

![icon](https://github.com/user-attachments/assets/46272e11-ced8-47e8-98c3-1bf137f1399d)

![1](https://github.com/user-attachments/assets/c3bbf1cb-8698-4dbb-8d99-836f19142483)
![2](https://github.com/user-attachments/assets/5bd4bc7a-0c46-4171-bbe4-bc4b700c4ef0)
![3](https://github.com/user-attachments/assets/b80c3f06-a300-4d39-bf0c-aa122b760678)

2025-02-17 04:43 UTC, nmfretz commented
Thanks again for submitting Mainsail @Julienpeps. I've made the final changes so that I don't hold you up any longer than I already have! Going live. 

<img width="1361" alt="image" src="https://github.com/user-attachments/assets/2de0cfea-0094-46ef-9c00-75395f02ff66" />

2025-02-17 04:43 UTC, merged