App Submission: Jackett
getumbrel/umbrel-apps pull request #665
Opened 2023-07-04 11:36 UTC by IMPranshu

This PR takes care of the issue https://github.com/getumbrel/umbrel-apps/issues/487
But additional testing is needed. I think we may need to whitelist something in order to get it completely. Anyways I have no idea need some reviews

# App Submission

### Jackett
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/jackett.svg
...

### Gallery images

![jackett-screenshot3](https://github.com/getumbrel/umbrel-apps/assets/43396684/01dd6c27-9ae8-49cb-97d5-842591f38a67)
![jackett-screenshot2](https://github.com/getumbrel/umbrel-apps/assets/43396684/23537f2a-8b11-46ec-a779-22b4a25d3e4e)
![jackett-screenshot1](https://github.com/getumbrel/umbrel-apps/assets/43396684/ead7f9f2-6c4d-46c3-9325-754dbd3886a5)

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

2023-08-04 23:26 UTC, nmfretz commented
>  I think we may need to whitelist something in order to get it completely. Anyways I have no idea need some reviews

Thanks @IMPranshu, I'll look into this

2023-09-25 13:26 UTC, ParthJadhav commented on jackett/umbrel-app.yml
> +submission: ""
@IMPranshu , Please add link to this PR in the submission.

2023-09-25 14:07 UTC, ParthJadhav requested changes
Hey @IMPranshu , It works on `umbrel-dev`. 

There's only one change i've mentioned above otherwise LGTM !

Thanks for the contribution ❤️

2023-09-25 14:55 UTC, ParthJadhav approved these changes
LGTM !

2023-09-27 09:29 UTC, ParthJadhav commented
Hey @IMPranshu, You asked about white listing directories at the start of the PR. Sorry I missed that. 

Regarding that:
If you go to this page: https://hub.docker.com/r/linuxserver/jackett/

and look at the `docker-compose.yml` in the `usage` section you'll find:

```yml
--
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /path/to/data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
```

Here it's suggested that you mount two volumes:
```yml
 volumes:
      - /path/to/data:/config
      - /path/to/blackhole:/downloads
```

If you want to do it with Umbrel then you will need to mount Umbrel's path:
```yml
 volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${APP_DATA_DIR}/blackhole:/downloads
```

After doing that you would also need to push those directories along with the changes. 
To push empty directories you would include `.gitkeep` file inside the directory.

```
- jackett 
-- docker-compose.yml
-- umbrel-app.yml
-- data
--- .gitkeep
-- blackhole
--- .gitkeep
```

2023-10-13 17:25 UTC, nmfretz commented
Thanks again for submitting Jackett @IMPranshu. And thanks for your review @ParthJadhav. This is going live to the app store now 🥼.

To bring this to the finish line, we have:
- changed the port to Jackett's default port (9117) so that users who search for troubleshooting tips online don't need to do any translations
- bind mounted the blackhole directory to the Umbrel downloads directory on the host
- added the data directory to this repo to ensure proper ownership/permissions when the app is installed
- bumped Jackett to the latest version
- whitelisted the api route in the app proxy
- added some set up instructions

2023-10-13 17:27 UTC, merged