App Submission: Seafile
getumbrel/umbrel-apps pull request #676
Opened 2023-07-11 05:29 UTC by IMPranshu

# App Submission

### SeaFile
...

### 256x256 SVG icon
https://github.com/IMPranshu/svg-logo/blob/main/seafile.svg

...

### Gallery images
![Screenshot from 2022-11-14 14-31-56](https://user-images.githubusercontent.com/43396684/201626008-d8235535-ac1c-4149-8dae-fdd22a07adb9.png)
![Screenshot from 2022-11-14 14-32-06](https://user-images.githubusercontent.com/43396684/201626052-cf0130a5-3e69-4b83-b8bf-e8c19b8eacca.png)
![Screenshot from 2022-11-14 14-32-19](https://user-images.githubusercontent.com/43396684/201626061-c0111b41-72df-4470-bc15-089c15d009f9.png)
![Screenshot from 2022-11-14 14-32-36](https://user-images.githubusercontent.com/43396684/201626070-1a271535-6c79-40e5-ad93-e2f5050e5bd3.png)
![Screenshot from 2022-11-14 14-32-44](https://user-images.githubusercontent.com/43396684/201626075-4ec30666-2a3a-44b0-ae35-50dc26a4d680.png)

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

2023-08-04 22:42 UTC, nmfretz commented
Awesome @IMPranshu, this has been requested in the past and is quite popular. I will review soon!

2023-08-08 18:48 UTC, nmfretz commented
Hey @IMPranshu, it looks like this might still be a work-in-progress so I have converted this PR to a Draft while you are working on it and testing. 

Here's a few things to check that I noticed at first glance:
- The Umbrel `app_proxy` container is missing from the `docker-compose.yml`. Was this intentional?
- seafile is running as root (may not be necessary).
- The images are quite old (~1yr).
- Can you please check if we can remove the custom `seafile-net` network and custom `container_name`'s, so that we simplify the yml and let Docker Compose automatically handle this? I think everything should still work correctly.
- The data directories for the volume bind mounts are missing from this repo.

Let me know when you have this working nicely and I'll review and test!

2023-09-13 16:16 UTC, swarupbhc commented
Hi, @nmfretz please review this.

2023-09-25 13:19 UTC, ParthJadhav commented on seafile/umbrel-app.yml
> +category: Files
Hey @IMPranshu , due to a recent change the category values should be lowercase. 

```suggestion
category: files
```

2023-09-25 14:04 UTC, ParthJadhav requested changes
Tested on Umbrel-dev server. Works fine. I didn't test further because I didn't know where to create an account to test it.

there are couple of changes which I've mentioned.

Thanks for the contribution ❤️

2023-11-17 19:44 UTC, johnpc commented
This is awesome! 

However it does require that you set these manually to the host-ip:port after installation, otherwise all uploads fail: 
![](https://forum-seafile-com-backups.s3.dualstack.us-east-1.amazonaws.com/original/2X/2/2a1e85862829bd83bed0983084fbc23f5677014d.png)

Additionally, the username/password of `me@example.com` and `asecret` are not conventional for umbrel. I think they should be changed (possibly `umbrel` and `moneyprintergobrrr` instead).

Finally, it is frustrating for me that the drive folder is nested under `app-data`. This means that if the app is deleted, all files uploaded via seafile are destroyed. I would prefer if it pointed to the data volume like ` - ${UMBREL_ROOT}/data/storage/seafile-data:/shared` for example.

Seafile is an excellent program and it certainly belongs in the umbrel app store. I hope this PR gets merged

2024-01-20 01:19 UTC, nmfretz commented
Alrighty, I went through this today and got Seafile working https://github.com/getumbrel/umbrel-apps/pull/676/commits/dfb9b366a5e640c2f61a26388f8324f738057954. This is pretty much ready to go! @IMPranshu @smolgrrr @johnpc may I please get one of you to test as well?

@johnpc:

> Is it possible to set those values to the correct ones by default using environment variables?

Yep, I set env vars so that uploading works out-of-the-box after installing as long as you upload from the UI using your main hostname... so `umbrel.local` for most people.

<img width="796" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/cb8441cf-0a72-4732-9a3e-e4e9813f87e2">



Users who want to customize this can do so in the UI and it will persist.


> Additionally, the username/password of me@example.com and asecret are not conventional for umbrel. I think they should be changed (possibly umbrel and moneyprintergobrrr instead).

Good call. I have changed the username to `umbrel` and the default password to a unique, deterministic one as we do for other apps. These values will be available to users in the app store when they install the app.

> Finally, it is frustrating for me that the drive folder is nested under app-data. This means that if the app is deleted, all files uploaded via seafile are destroyed. I would prefer if it pointed to the data volume like  - ${UMBREL_ROOT}/data/storage/seafile-data:/shared for example.

Ya, I hear you. The reason we do this is because most users would expect deleting an app to also delete all data associated with it (especially if they are doing so to free up room on their device). Let me chat with the team and get back to you on this.

2024-01-20 05:08 UTC, IMPranshu commented
Tested this on my Pi, working 💪

2024-01-23 19:18 UTC, nmfretz commented
Thanks @IMPranshu!

I added some additional instructions to the app description. I'll merge this once we have the gallery assets ready.

2024-01-24 04:22 UTC, IMPranshu commented
😎

2024-02-23 18:02 UTC, nmfretz commented
Gallery assets are now ready! Going live to the app store 🎉

https://github.com/getumbrel/umbrel-apps-gallery/tree/master/seafile
<img width="1383" alt="image" src="https://github.com/getumbrel/umbrel-apps/assets/85373263/7c1ccbac-0f22-4f95-aef9-2d1789aa88eb">

2024-02-23 18:02 UTC, merged