Add Fenrus Dashboard
getumbrel/umbrel-apps pull request #79
Opened 2022-07-18 22:59 UTC by awholegnuworld

This is my first time using docker, please be patient. 😅 I don't know if I did this correctly.

This is not my app, it is just an app that I thought was cool.
https://github.com/revenz/Fenrus

Image for app store:
![](https://user-images.githubusercontent.com/958400/157801403-64cc7b99-f81d-41b6-85f7-47546bd904a9.png)

2022-07-30 13:53 UTC, lukechilds commented
>This is my first time using docker, please be patient. 😅 I don't know if I did this correctly.

No worries!

Your `umbrel-app.yml` file looked great, however the `docker-compose.yml` file is currently just the template. You need to fill in the values to run a Fenrus Docker container and setup any required environment variables or volumes.

2022-07-30 13:55 UTC, lukechilds requested changes

2022-07-30 13:55 UTC, lukechilds commented on fenrus/docker-compose.yml
> +version: "1.0"
This file needs to be populated.

2022-08-25 12:01 UTC, nevets963 commented
Hey @awholegnuworld Is there something that can be done to help progress this PR? Just checking in to see if you're still working on it?

Steve

2022-08-25 12:05 UTC, awholegnuworld commented
> Hey @awholegnuworld Is there something that can be done to help progress this PR? Just checking in to see if you're still working on it?
> 
> 
> 
> Steve

Thanks for checking in! Yeah, I'm still working on it, but school just started and I have other things to do right now. The main thing that needs to be done is filling in the docker file.

2023-02-11 22:36 UTC, awholegnuworld commented
Ok, I'm sorry for waiting so long. I finally had some time off and remembered to work on this.

2023-02-13 22:51 UTC, awholegnuworld commented
Can do.

2023-05-18 22:09 UTC, nmfretz commented
Hey @awholegnuworld did you have any luck getting the developer to consider versioned Docker images? If not, would you still like to keep this PR open?

2023-07-10 17:23 UTC, nmfretz commented
@awholegnuworld just checking in again to see if you would like to keep this PR open.

2023-07-12 22:11 UTC, awholegnuworld commented
I'm fine to close the PR. I haven't been working with my Umbrel lately.

2023-07-14 05:52 UTC, nmfretz commented
Thanks @awholegnuworld. Please open this again if you end up wanting to work on it!

2023-07-14 05:52 UTC, closed without merging